import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  variable: '--font-poppins',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Estate Atlas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.variable}
      >
         <Providers>
      
        <main className="min-h-screen">
          {children}
        </main>
            </Providers>
       
      </body>
    </html>
  );
}
